name: Render Deploy

on:
  push:
#動作確認のため一旦コメントアウト
#    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK__URL }}
        run: |
          echo "Deploy URL: $deploy_url"
          curl "$deploy_url"
